/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('models/robot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.robotv5_1.geometry} material={materials['Plastic_-_Translucent_Glossy_(Red).003']} />
      <mesh geometry={nodes.robotv5_2.geometry} material={materials['Display_-_7_Segments_-_LED']} />
      <mesh geometry={nodes.robotv5_3.geometry} material={materials['ABS_(White)_(1).003']} />
      <mesh geometry={nodes.robotv5_4.geometry} material={materials['ABS_(White).003']} />
      <mesh geometry={nodes.robotv5_5.geometry} material={materials['ABS_(lightgray).003']} />
      <mesh geometry={nodes.robotv5_6.geometry} material={materials['Steel_-_Satin.003']} />
      <mesh geometry={nodes.robotv5_7.geometry} material={materials['ABS_(White)_(1)_1.003']} />
      <mesh geometry={nodes.robotv5_8.geometry} material={materials['Rubber_-_Soft.003']} />
      <mesh geometry={nodes.robotv5_9.geometry} material={materials['Opaque(53,53,53).003']} />
      <mesh geometry={nodes.robotv5_10.geometry} material={materials['ABS_(darkgray)_(1)_(1).003']} />
      <mesh geometry={nodes.robotv5_11.geometry} material={materials['Opaque(63,63,63).003']} />
      <mesh geometry={nodes.robotv5_12.geometry} material={materials['ABS_(darkgray).003']} />
      <mesh geometry={nodes.robotv5_13.geometry} material={materials['ABS_(darkgray)_(1)_(2).003']} />
      <mesh geometry={nodes.robotv5_14.geometry} material={materials['Opaque(163,169,170).003']} />
      <mesh geometry={nodes.robotv5_15.geometry} material={materials['Opaque(73,73,73).003']} />
      <mesh geometry={nodes.robotv5_16.geometry} material={materials['Opaque(165,159,143).003']} />
      <mesh geometry={nodes.robotv5_17.geometry} material={materials['Opaque(217,196,147).003']} />
      <mesh geometry={nodes.robotv5_18.geometry} material={materials['Opaque(229,202,158).003']} />
      <mesh geometry={nodes.robotv5_19.geometry} material={materials['Opaque(192,192,192).003']} />
      <mesh geometry={nodes.robotv5_20.geometry} material={materials['Opaque(255,255,128).003']} />
      <mesh geometry={nodes.robotv5_21.geometry} material={materials['Opaque(208,208,208).003']} />
      <mesh geometry={nodes.robotv5_22.geometry} material={materials['Opaque(232,173,35).003']} />
      <mesh geometry={nodes.robotv5_23.geometry} material={materials['Opaque(40,40,40).003']} />
      <mesh geometry={nodes.robotv5_24.geometry} material={materials['Opaque(64,64,64).003']} />
      <mesh geometry={nodes.robotv5_25.geometry} material={materials['Opaque(25,25,25).003']} />
      <mesh geometry={nodes.robotv5_26.geometry} material={materials['Opaque(196,197,196).003']} />
      <mesh geometry={nodes.robotv5_27.geometry} material={materials['Opaque(203,203,203).003']} />
      <mesh geometry={nodes.robotv5_28.geometry} material={materials['Opaque(255,255,255).003']} />
      <mesh geometry={nodes.robotv5_29.geometry} material={materials['Opaque(204,207,204).003']} />
      <mesh geometry={nodes.robotv5_30.geometry} material={materials['Opaque(26,26,26).003']} />
      <mesh geometry={nodes.robotv5_31.geometry} material={materials['Opaque(127,127,127).003']} />
      <mesh geometry={nodes.robotv5_32.geometry} material={materials['Opaque(160,160,160).003']} />
      <mesh geometry={nodes.robotv5_33.geometry} material={materials['Opaque(245,245,246).003']} />
      <mesh geometry={nodes.robotv5_34.geometry} material={materials['Opaque(244,229,167).003']} />
      <mesh geometry={nodes.robotv5_35.geometry} material={materials['Opaque(45,45,45).003']} />
      <mesh geometry={nodes.robotv5_36.geometry} material={materials['Opaque(255,207,128).003']} />
      <mesh geometry={nodes.robotv5_37.geometry} material={materials['Opaque(230,230,230).003']} />
      <mesh geometry={nodes.robotv5_38.geometry} material={materials['Opaque(77,77,77).003']} />
      <mesh geometry={nodes.robotv5_39.geometry} material={materials['Opaque(0,127,0).003']} />
      <mesh geometry={nodes.robotv5_40.geometry} material={materials['Opaque(255,191,0).003']} />
      <mesh geometry={nodes.robotv5_41.geometry} material={materials['Opaque(123,97,74).003']} />
      <mesh geometry={nodes.robotv5_42.geometry} material={materials['Opaque(211,212,213).003']} />
      <mesh geometry={nodes.robotv5_43.geometry} material={materials['Opaque(30,30,30).003']} />
      <mesh geometry={nodes.robotv5_44.geometry} material={materials['Opaque(242,236,238).003']} />
      <mesh geometry={nodes.robotv5_45.geometry} material={materials['Opaque(160,165,169).003']} />
      <mesh geometry={nodes.robotv5_46.geometry} material={materials['Opaque(205,183,57).003']} />
      <mesh geometry={nodes.robotv5_47.geometry} material={materials['Opaque(201,26,9).003']} />
      <mesh geometry={nodes.robotv5_48.geometry} material={materials['Opaque(178,178,178).003']} />
      <mesh geometry={nodes.robotv5_49.geometry} material={materials['Opaque(0,132,229).003']} />
      <mesh geometry={nodes.robotv5_50.geometry} material={materials['Opaque(0,132,229)_(1).003']} />
      <mesh geometry={nodes.robotv5_51.geometry} material={materials['Opaque(8,229,0).003']} />
      <mesh geometry={nodes.robotv5_52.geometry} material={materials['Opaque(229,234,237).003']} />
      <mesh geometry={nodes.robotv5_53.geometry} material={materials['Opaque(198,193,188).003']} />
      <mesh geometry={nodes.robotv5_54.geometry} material={materials['ABS_(White)_(2).001']} />
      <mesh geometry={nodes.robotv5_55.geometry} material={materials['Opaque(152,170,175).003']} />
      <mesh geometry={nodes.robotv5_56.geometry} material={materials['Opaque(179,179,179).003']} />
      <mesh geometry={nodes.robotv5_57.geometry} material={materials['Opaque(246,246,243).003']} />
      <mesh geometry={nodes.robotv5_58.geometry} material={materials['Opaque(237,206,195).003']} />
      <mesh geometry={nodes.robotv5_59.geometry} material={materials['Opaque(255,145,42).003']} />
      <mesh geometry={nodes.robotv5_60.geometry} material={materials['tan.003']} />
      <mesh geometry={nodes.robotv5_61.geometry} material={materials['ABS_(darkgray)_(1).003']} />
    </group>
  )
}

useGLTF.preload('models/robot.glb')
