/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wrorobot.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/wrorobot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Untitled_1.geometry} material={materials['Plastic_-_Translucent_Glossy_(Red)']} />
      <mesh geometry={nodes.Untitled_2.geometry} material={materials['ABS_(White)']} />
      <mesh geometry={nodes.Untitled_3.geometry} material={materials['ABS_(White)_(1)_1']} />
      <mesh geometry={nodes.Untitled_4.geometry} material={materials['Rubber_-_Soft']} />
      <mesh geometry={nodes.Untitled_5.geometry} material={materials['Opaque(53,53,53)']} />
      <mesh geometry={nodes.Untitled_6.geometry} material={materials['ABS_(darkgray)_(1)_(1)']} />
      <mesh geometry={nodes.Untitled_7.geometry} material={materials['ABS_(darkgray)']} />
      <mesh geometry={nodes.Untitled_8.geometry} material={materials['ABS_(darkgray)_(1)_(2)']} />
      <mesh geometry={nodes.Untitled_9.geometry} material={materials['Opaque(163,169,170)']} />
      <mesh geometry={nodes.Untitled_10.geometry} material={materials['Opaque(73,73,73)']} />
      <mesh geometry={nodes.Untitled_11.geometry} material={materials['Opaque(165,159,143)']} />
      <mesh geometry={nodes.Untitled_12.geometry} material={materials['Opaque(217,196,147)']} />
      <mesh geometry={nodes.Untitled_13.geometry} material={materials['Opaque(229,202,158)']} />
      <mesh geometry={nodes.Untitled_14.geometry} material={materials['Opaque(192,192,192)']} />
      <mesh geometry={nodes.Untitled_15.geometry} material={materials['Opaque(255,255,128)']} />
      <mesh geometry={nodes.Untitled_16.geometry} material={materials['Opaque(208,208,208)']} />
      <mesh geometry={nodes.Untitled_17.geometry} material={materials['Opaque(232,173,35)']} />
      <mesh geometry={nodes.Untitled_18.geometry} material={materials['Opaque(40,40,40)']} />
      <mesh geometry={nodes.Untitled_19.geometry} material={materials['Opaque(196,197,196)']} />
      <mesh geometry={nodes.Untitled_20.geometry} material={materials['Opaque(203,203,203)']} />
      <mesh geometry={nodes.Untitled_21.geometry} material={materials['Opaque(255,255,255)']} />
      <mesh geometry={nodes.Untitled_22.geometry} material={materials['Opaque(204,207,204)']} />
      <mesh geometry={nodes.Untitled_23.geometry} material={materials['Opaque(26,26,26)']} />
      <mesh geometry={nodes.Untitled_24.geometry} material={materials['Opaque(127,127,127)']} />
      <mesh geometry={nodes.Untitled_25.geometry} material={materials['Opaque(245,245,246)']} />
      <mesh geometry={nodes.Untitled_26.geometry} material={materials['Opaque(244,229,167)']} />
      <mesh geometry={nodes.Untitled_27.geometry} material={materials['Opaque(45,45,45)']} />
      <mesh geometry={nodes.Untitled_28.geometry} material={materials['Opaque(255,207,128)']} />
      <mesh geometry={nodes.Untitled_29.geometry} material={materials['Opaque(230,230,230)']} />
      <mesh geometry={nodes.Untitled_30.geometry} material={materials['Opaque(77,77,77)']} />
      <mesh geometry={nodes.Untitled_31.geometry} material={materials['Opaque(0,127,0)']} />
      <mesh geometry={nodes.Untitled_32.geometry} material={materials['Opaque(255,191,0)']} />
      <mesh geometry={nodes.Untitled_33.geometry} material={materials['Opaque(123,97,74)']} />
      <mesh geometry={nodes.Untitled_34.geometry} material={materials['Opaque(211,212,213)']} />
      <mesh geometry={nodes.Untitled_35.geometry} material={materials['Opaque(30,30,30)']} />
      <mesh geometry={nodes.Untitled_36.geometry} material={materials['Opaque(242,236,238)']} />
      <mesh geometry={nodes.Untitled_37.geometry} material={materials['Opaque(205,183,57)']} />
      <mesh geometry={nodes.Untitled_38.geometry} material={materials['Opaque(201,26,9)']} />
      <mesh geometry={nodes.Untitled_39.geometry} material={materials['Opaque(178,178,178)']} />
      <mesh geometry={nodes.Untitled_40.geometry} material={materials['Opaque(0,132,229)']} />
      <mesh geometry={nodes.Untitled_41.geometry} material={materials['Opaque(8,229,0)']} />
      <mesh geometry={nodes.Untitled_42.geometry} material={materials['Opaque(229,234,237)']} />
      <mesh geometry={nodes.Untitled_43.geometry} material={materials['Opaque(198,193,188)']} />
      <mesh geometry={nodes.Untitled_44.geometry} material={materials['Opaque(152,170,175)']} />
      <mesh geometry={nodes.Untitled_45.geometry} material={materials['Opaque(179,179,179)']} />
      <mesh geometry={nodes.Untitled_46.geometry} material={materials['Opaque(246,246,243)']} />
      <mesh geometry={nodes.Untitled_47.geometry} material={materials['Opaque(237,206,195)']} />
      <mesh geometry={nodes.Untitled_48.geometry} material={materials['Opaque(255,145,42)']} />
      <mesh geometry={nodes.Untitled_49.geometry} material={materials.tan} />
      <mesh geometry={nodes.Untitled_50.geometry} material={materials['Display_-_7_Segments_-_LED']} />
      <mesh geometry={nodes.Untitled_51.geometry} material={materials['ABS_(White)_(1)']} />
      <mesh geometry={nodes.Untitled_52.geometry} material={materials['ABS_(lightgray)']} />
      <mesh geometry={nodes.Untitled_53.geometry} material={materials['ABS_(darkgray)']} />
      <mesh geometry={nodes.Untitled_54.geometry} material={materials['Opaque(63,63,63)']} />
      <mesh geometry={nodes.Untitled_55.geometry} material={materials['Opaque(0,132,229)_(1)']} />
    </group>
  )
}

useGLTF.preload('/models/wrorobot.glb')
